quarkus.application.name=task-service
quarkus.http.port=8081
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.db-name=tasks_db
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.flyway.migrate-at-start=true

%prod.quarkus.datasource.username=${TASKS_DB_USERNAME:lifeos}
%prod.quarkus.datasource.password=${TASKS_DB_PASSWORD:lifeos}
%prod.quarkus.datasource.jdbc.url=${TASKS_DB_URL:jdbc:postgresql://localhost:5432/tasks_db}
%prod.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

mp.messaging.outgoing.task-completed.connector=smallrye-kafka
mp.messaging.outgoing.task-completed.topic=task.completed.events
mp.messaging.outgoing.task-completed.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.task-reopened.connector=smallrye-kafka
mp.messaging.outgoing.task-reopened.topic=task.reopened.events
mp.messaging.outgoing.task-reopened.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
